config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :pages
  resources :monsters, only: %i[index show] do
    collection do
      get 'search_results'
    end
  end

  get '/static/:permalink', to: 'pages#permalink', as: 'permalink'
  root to: 'monsters#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attribute.rb
# frozen_string_literal: true

class Attribute < ApplicationRecord
  has_many :monster_cards
  has_many :spell_cards
  has_many :trap_cards
  has_and_belongs_to_many :monster_cards
  has_and_belongs_to_many :trap_cards
  has_and_belongs_to_many :trap_cards

  validates :name, presence: true
  validates :description, presence: true
end

app/models/monster_card.rb
# frozen_string_literal: true

class MonsterCard < ApplicationRecord
  # belongs_to :race
  # belongs_to :type
  # belongs_to :attribute

  # has_and_belongs_to_many :type
  # has_and_belongs_to_many :race
  # has_and_belongs_to_many :attribute

  # validates :name, presence: true
  # validates :atk, presence: true, numericality: { only_float: true }
  # validates :def, presence: true, numericality: { only_float: true }
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/race.rb
# frozen_string_literal: true

class Race < ApplicationRecord
  has_many :monster_cards
  has_many :spell_cards
  has_many :trap_cards
  has_and_belongs_to_many :monster_cards
  has_and_belongs_to_many :trap_cards
  has_and_belongs_to_many :trap_cards

  validates :name, presence: true
  validates :description, presence: true
end

app/models/spell_card.rb
class SpellCard < ApplicationRecord
  belongs_to :attribute
  belongs_to :race
  belongs_to :type
  has_and_belongs_to_many :type
  has_and_belongs_to_many :race
  has_and_belongs_to_many :attribute

  validates :name, presence: true
  validates :description, presence: true
end

app/models/trap_card.rb
# frozen_string_literal: true

class TrapCard < ApplicationRecord
  belongs_to :type
  belongs_to :attribute
  belongs_to :race
  has_and_belongs_to_many :type
  has_and_belongs_to_many :race
  has_and_belongs_to_many :attribute

  validates :name, presence: true
  validates :description, presence: true
end

app/models/type.rb
# frozen_string_literal: true

class Type < ApplicationRecord
  has_many :monster_cards
  has_many :spell_cards
  has_many :trap_cards
  has_and_belongs_to_many :monster_cards
  has_and_belongs_to_many :trap_cards
  has_and_belongs_to_many :trap_cards

  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/monsters_controller.rb
# frozen_string_literal: true

class MonstersController < ApplicationController
  def index
    @monsters = MonsterCard.all
  end

  def show
    @monsters = MonsterCard.find(params[:id])
  end

  def search_results; end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  before_action :set_page, only: %i[show edit update destroy]

  def permalink
    @page = Page.find_by_permalink(params[:permalink])
    if @page
      render :show
    else
      redirect_to root_path
    end
  end

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show; end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit; end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def page_params
    params.require(:page).permit(:title, :content, :permalink)
  end
end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/traps_controller.rb
class TrapsController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/helpers/traps_helper.rb
module TrapsHelper
end

app/views/about/index.html.erb
<h1>About Page</h1>
<p>Hi the data source that I'm using, is a Yugioh api that gets all the Yugioh cards that have been created
and will post those cards Description, Atk, Def, Race, Type, Attribute onto the page.</p>
<a href="https://db.ygoprodeck.com/api-guide/">Here is the api that I'm using.</a>
<p>Here's my ERD of my diagram</p>
<%= link_to image_tag('erd.png')%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yugioh</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <nav>
    <ul>
    <li><%= link_to 'Home', root_path %>
    <li><%= link_to 'About', permalink_path(permalink: 'about_us')%></li>
    </ul>
    </nav>
    </header>
    <%= form_with(url: "/search", method: "get") do %>
    <%= label_tag(:query, "Search for:") %>
    <%= text_field_tag(:query) %>
    <%= submit_tag("Search") %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/monsters/index.html.erb
<h1>Monster Card</h1>

<% @monsters.each do |monster| %>
  <h2><%= link_to monster.name %></h2>
  <p><%= monster.description %> </p>
 <% end%>

app/views/monsters/search_results.html.erb
Search Results go here

app/views/monsters/show.html.erb
<h1>Monster Card</h1>
<h2><%=  @monsters.name %></h2>

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :permalink %>
    <%= form.text_field :permalink %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Permalink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.content %></td>
        <td><%= page.permalink %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @page.title %>
</p>

<p>
  <strong>Content:</strong>
  <p>Hi the data source that I'm using, is a Yugioh api that gets all the Yugioh cards that have been created
  and will post those cards Description, Atk, Def, Race, Type, Attribute onto the page.</p>
  <a href="https://db.ygoprodeck.com/api-guide/">Here is the api that I'm using.</a>
  <p>Here's my ERD of my diagram</p>
  <%= link_to image_tag('erd.png')%>
</p>

<%#= link_to 'Edit', edit_page_path(@page) %>
<%#= link_to 'Back', pages_path %>

app/views/spells/index.html.erb
<h1>Spells#index</h1>
<p>Find me in app/views/spells/index.html.erb</p>

app/views/spells/show.html.erb
<h1>Spells#show</h1>
<p>Find me in app/views/spells/show.html.erb</p>

app/views/traps/index.html.erb
<h1>Traps#index</h1>
<p>Find me in app/views/traps/index.html.erb</p>

app/views/traps/show.html.erb
<h1>Traps#show</h1>
<p>Find me in app/views/traps/show.html.erb</p>